version: '3.8'
services:
  web:
    build: .
    ports:
      - "8085:80"
    volumes:
      - ./ebrigade:/var/www/html
    environment:
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - FROM_EMAIL=${FROM_EMAIL}
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ebrigade
      MYSQL_USER: ebrigadeuser
      MYSQL_PASSWORD: ebrigadepass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
